export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESSFULLY = 'FETCH_USERS_SUCCESSFULLY';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
